name: rh
favicon: null
layout_spectrum: 0.88508
typography_spectrum: 0.82659
title: Finding My Fight
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#626365'
    - '#828385'
    - '#c8c8c9'
    - '#6db9a9'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: null
    url: null
