name: rh
favicon: null
layout_spectrum: 0.88508
typography_spectrum: 0.82659
title: Finding My Fight
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#e8e7e5'
    - '#c9c8c6'
    - '#2e2e22'
    - '#7b7774'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: null
    url: null
